# FastAPI Dockerfile
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./app /app
#

RUN pip install -r /app/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Pytorch Dockerfile
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg libsm6 libxext6  -y

COPY requirements.txt /tmp/requirements.txt
RUN pip --no-cache-dir install -r /tmp/requirements.txt

WORKDIR /mnt/
COPY . /app/
CMD ["python3", "/app/main.py"]
